### ISSUE TITLE
EOS Transaction sign sample

### ISSUE THREAD

**Issue by hossainiir** [primes-network/eosdart_ecc#1]
Hi, can you provide a sample to show how we can sign and push a transaction to mainnet or testnet?

**Comment by fzxu** [comment]
this is working in progress. A very simple API will be provided in: https://github.com/primes-network/eosdart

**Comment by hossainiir** [comment]
Any roadmap for features?
Also, I saw the eosdart project it has very simple actions!

**Comment by fzxu** [comment]
the push transaction is the next feature in progress. The goal is to make it very easy to use and integrate with flutter.

**Comment by hossainiir** [comment]
Currently, we had a discussion on eos developer Telegram group about how to push a transaction in flutter apps and I introduce your dart package, I hope this feature complete as soon as possible!!
Also when this feature has been added please let me know, Thanks.

**Comment by fzxu** [comment]
feel free to watch eosdart, you will get notification once there is releases. I'll close this issue.
