### ISSUE TITLE
signHash generates noncanonical signatures.

### ISSUE THREAD

**Issue by hossainiir** [primes-network/eosdart_ecc#2]
Hi, I created a library that generates transaction and then I used eosdart_ecc signHash to create signature but most of the generated signatures are not canonical !!

I think this is a bug.

**Comment by fzxu** [comment]
Could you provide the data for testing? I am also working on push transaction in project: https://github.com/primes-network/eosdart

**Comment by 7flash** [comment]
I have the same issue. Here is an example:
```
  var transactionHash = [163, 116, 129, 86, 200, 123, 227, 202, 142, 90, 242, 133, 92, 102, 161, 201, 85, 238, 77, 107, 136, 182, 62, 94, 148, 35, 190, 52, 12, 66, 27, 35];

  EOSPrivateKey privateKey = EOSPrivateKey.fromString(
    '5Jsh4oyLjiT8AP78LXpCv1Kh7gyrpfm2KnakjzE2iP2pM57S89r'
  );

    EOSSignature signature = privateKey.signHash(Uint8List.fromList(transactionHash));
    
    print(signature.toString()); // SIG_K1_KgHbkQ8XqiWQ64mrHVFMcbKnc54XLy6QjoDbaegknotFxvGfkG9HdeDHyHgA87MC7UUSWkyDgmaRxJjqXH5mGQsZ9AqDUe
```

In comparison, eosjs generates another signature for the same transaction:
```
SIG_K1_KhLpBJV2cusu7vqSWMiFYrzcLSiocPY5KEajAJ6ZDmYCurFv9uFXuK6TG6n7PyyJrZnJmwqaHgr7C9Rb9Jg19EKzcPpCH4
```

**Comment by hossainiir** [comment]
Here is an example :
`
hash = "f4a3f04bae96e9b9e3421b82e68b667080264ee9693b3d0b19dd2a6d50b8aec9"private key = "5HxT6prWB8VuXkoAaX3eby8bWjquMtCvGuakhC8tGEiPSHfsQLR"
`

**Comment by hossainiir** [comment]
Here is an example :
```
var hash = "f4a3f04bae96e9b9e3421b82e68b667080264ee9693b3d0b19dd2a6d50b8aec9"; 
var private_key = "5HxT6prWB8VuXkoAaX3eby8bWjquMtCvGuakhC8tGEiPSHfsQLR";
```
Generated signature with eosdart : 
```
var sig = "SIG_K1_K4B6mXLkPmsNCtpfrhre6hfqq7fUQ2d7BDmpgwieKMdvstJAdo4vHbnDvuRCM9juRsPuetKBUv2p1FjF9kDWdHN2W4ZToc";
```
Generated signature with eosjs:
```
var sig = "SIG_K1_Kdfe9wknSAKBmgwb3L53CG8KosoHhZ69oVEJrrH5YuWx4JVcJdn1ZV3MU25AVho4mPbeSKW79DVTBAAWj7zGbHTByF1JXU";
```

**Comment by hossainiir** [comment]
> I have the same issue. Here is an example:
> 
> ```
>   var transactionHash = [163, 116, 129, 86, 200, 123, 227, 202, 142, 90, 242, 133, 92, 102, 161, 201, 85, 238, 77, 107, 136, 182, 62, 94, 148, 35, 190, 52, 12, 66, 27, 35];
> 
>   EOSPrivateKey privateKey = EOSPrivateKey.fromString(
>     '5Jsh4oyLjiT8AP78LXpCv1Kh7gyrpfm2KnakjzE2iP2pM57S89r'
>   );
> 
>     EOSSignature signature = privateKey.signHash(Uint8List.fromList(transactionHash));
>     
>     print(signature.toString()); // SIG_K1_KgHbkQ8XqiWQ64mrHVFMcbKnc54XLy6QjoDbaegknotFxvGfkG9HdeDHyHgA87MC7UUSWkyDgmaRxJjqXH5mGQsZ9AqDUe
> ```
> In comparison, eosjs generates another signature for the same transaction:
> 
> ```
> SIG_K1_KhLpBJV2cusu7vqSWMiFYrzcLSiocPY5KEajAJ6ZDmYCurFv9uFXuK6TG6n7PyyJrZnJmwqaHgr7C9Rb9Jg19EKzcPpCH4
> ```

I checked your hash and signature with eosjs and eosdart they were same and signature was 
``` SIG_K1_KgHbkQ8XqiWQ64mrHVFMcbKnc54XLy6QjoDbaegknotFxvGfkG9HdeDHyHgA87MC7UUSWkyDgmaRxJjqXH5mGQsZ9AqDUe ```
![image](https://user-images.githubusercontent.com/5255022/55679123-18687a00-591b-11e9-911b-16fa8eea7a7e.png)

**Comment by hossainiir** [comment]
Also, I think BigInt operations and nonce are caused this problem.

https://github.com/primes-network/eosdart_ecc/blob/9328f4c2e86d4721462f973b0de7000326121430/lib/src/key.dart#L164
https://github.com/primes-network/eosdart_ecc/blob/9328f4c2e86d4721462f973b0de7000326121430/lib/src/key.dart#L165

https://github.com/EOSIO/eosjs-ecc/blob/6d7cbe332cc332f15d0aad6957a6fc034043cfb9/src/signature.js#L210

**Comment by hossainiir** [comment]
Any update or fix for this issue?

**Comment by fzxu** [comment]
As your said, the signature signed by this is the same as eosjs-ecc, both generates `SIG_K1_KgHbkQ8XqiWQ64mrHVFMcbKnc54XLy6QjoDbaegknotFxvGfkG9HdeDHyHgA87MC7UUSWkyDgmaRxJjqXH5mGQsZ9AqDUe`. At this point I am not sure if it actually the issue of this project or the way you deal with the transaction. 

I am working on the eosdart lib, will find out more.

**Comment by fzxu** [comment]
@hossainiir  added the support for canonical signatures and one test case from you. It should be fixed. Let me know.
